### ISSUE TITLE
 Mod not loading build 97

### ISSUE THREAD

**Issue by MRtosti** [WallyCZ/DVRouteManager#6]
When I started the game the mod didn't work then I looked in the logs and there was an error code

[DVRouteManager] [Error] Error trying to call 'DVRouteManager.Module.Load'.
[DVRouteManager] [Exception] TargetInvocationException - Exception has been thrown by the target of an invocation. 

Is there a way to fix this?

**Comment by anon533566** [comment]
if you had checked my previous post you would have known this mod is outdated, if you read the description it clearly states what version it is compatible with your options are, downgrade to Build 91 (OVERHAULED) which is stated as supported version, OR.. wait till a update is provided.  the dev did start on it, but it has been quiet. unknown why, or if the dev has run into issues or perhaps, real life health or war has gotten in his/her way of being able to update it.

till there is a update, there's no fix and no one else will simply make a fix either as its impossible unless you know programming language... which quite frankly 99% of the downloaders/users lack as a skill... besides the fact before anyone could even share a potential fix... without proper re-upload permission they are unlikely to share it as it is considered copying theft otherwise. 

in short terms, the mod is severely broken by the new update, he/she has to completely re-write his mod and smart-ai and route manager functions. these are some hefty big coding functions they have managed to somehow make, but trust me when i say that this is FARRRRRR from easy or a "quick" fix like it is with cheat tables or trainers where a simple address needs to be researched and reset. just as a ending note, i am not trying to be like a jerk or something. hope you do find it informative and either enjoy the game without it (for now) or choose to downgrade, which in my personal opinion is also worth it just to see how nice this worked before if you never had it before. :) take care!

side note, if you do downgrade, backup your NEW Build 97 profile first prior to downgrading, as it may bork your save file else due to added new items which go missing in the downgrade. ^

**Comment by MRtosti** [comment]
Hello Anon

Thank you for your message and your explanation, it's a shame that no one knows if there will ever be an update, but then we'll just have to wait and see.

Take care

**Comment by MRtosti** [comment]
Hello Anon

Thank you for your message and your explanation, it's a shame that no one knows if there will ever be an update, but then we'll just have to wait and see.

Take care
